### ISSUE TITLE
Dashicons preview html doesn't look OK

### ISSUE THREAD

**Issue by toonvandeputte** [WordPress/dashicons#277] opened 2018-03-02 15:10 UTC
The height of the i element containing the icon is not set in icon-font/dashicons.html, causing the icons to be cut off (on Firefox)
<img width="624" alt="screen shot 2018-03-02 at 16 09 19" src="https://user-images.githubusercontent.com/6859906/36905692-45a62602-1e34-11e8-8213-6d3910246fe5.png">

**Comment by field2** [comment] 2018-03-02 17:12
I noticed that too. Adding height:32px after line 44 seems to fix

**Comment by toonvandeputte** [comment] 2018-03-04 19:54
I think it might not be that easy to solve, since this file appears to be generated from one of the node modules that is required by the build process. So it might be an issue in that project which the maintainers there need to address.
I'm currently on a different machine and don't have my local copy of dashicons at hand, so I don't know which module it is, exactly, but searching for the relevant css class yields its folder.

**Comment by Zodiac1978** [comment] 2020-03-28 09:59
Is this bug still valid?

**Comment by jasmussen** [comment] 2020-04-20 10:49
I can't reproduce, so I'm closing for now!

<img width="779" alt="Screenshot 2020-04-20 at 12 49 22" src="https://user-images.githubusercontent.com/1204802/79743734-63c2b000-8305-11ea-9d67-f62cd2fba68d.png">

**Closed by jasmussen** 2020-04-20 10:49 UTC
Labels: bug
