### ISSUE TITLE
Add Dashicon for linkedin

### ISSUE THREAD

**Issue by aslamshekh** [WordPress/dashicons#365] opened 2019-06-11 10:05 UTC
Please add Dashicon for Linkedin in Social category.

**Comment by Rmanaf** [comment] 2019-07-06 16:35
Duplicate of #358

**Comment by Rubsel** [comment] 2019-08-14 09:38
Im with this one since we already have Facebook. Twitter, Instagram and Google there, LinkedIn is an obvious choice.

**Comment by Zodiac1978** [comment] 2020-03-11 14:19
Duplicate of #309

**Closed** 2020-03-17 20:31 UTC
